name: networq:skype
description: Skypes types
license: MIT

dependencies:
  networq:core: latest

widgets:
  skypeUserProperties:
    type: networq:skype:user
    hook: properties
    label: Skype properties